namenodeEndpoint: hdfs://10.150.0.17:9000/
hdfsConfigFile: /home/ubuntu/repos/hops/hadoop-dist/target/hadoop-3.2.0.3-SNAPSHOT/etc/hadoop/hdfs-site.xml
followers:
        -
                ip: 10.150.0.20
                user: ben
