namenodeEndpoint: hdfs://10.150.0.10:9000/
hdfsConfigFile: /home/ubuntu/repos/hops/hadoop-dist/target/hadoop-3.2.0.3-SNAPSHOT/etc/hadoop/hdfs-site.xml
followers:
        -
                ip: 10.150.0.20
                user: ben
        -
                ip: 10.150.0.55
                user: ben
        -
                ip: 10.150.0.122
                user: ben
        -
                ip: 10.150.0.39
                user: ben
        -
                ip: 10.150.0.41
                user: ben
        -
                ip: 10.150.0.40
                user: ben
        -
                ip: 10.150.0.42
                user: ben
        -
                ip: 10.150.0.33
                user: ben
        -
                ip: 10.150.0.27
                user: ben
        -
                ip: 10.150.0.22
                user: ben
        -
                ip: 10.150.0.12
                user: ben
        -
                ip: 10.150.0.14
                user: ben
        -
                ip: 10.150.0.32
                user: ben
        -
                ip: 10.150.0.28
                user: ben
        -
                ip: 10.150.0.21
                user: ben